### PR TITLE
Fix navigation on navbar to sync with scrolling.

### PR DESCRIPTION
**Pull request by sennav**
I explained it on #20

### CODE REVIEW

**Comment by sennav** [comment]
Should it be merged to master?

**Comment by su-ex** [comment]
Imagine somebody has JavaScript disabled:
With href it just goes to the anker, with data-target it needs js to go to the section.
If there''s no other solution I think it's better the way it's now.

**Comment by sennav** [comment]
You're right, I returned the `href` to it's place, there is no problem to keep both. The use of data-target still corrects the issue.

**Comment by su-ex** [comment]
Sure, that's also a way, so easy. :)

**Comment by davidtmiller** [comment]
I'm still on the fence with this one. I kind of don't want to replace href with data-target because href is more recognizable and beginner-friendly.

**Comment by sennav** [comment]
There is any problem in keeping both of them?

**Comment by davidtmiller** [comment]
Other than confusion on the newbies part I don't see any problem with keeping both. The main issue is that I don't want to confuse the beginners

**Comment by sennav** [comment]
I can't reproduce the bug anymore so I guess it fixed itself with some kind of update. I'm closing this.

**Comment by davidtmiller** [comment]
It might have been fixed in another pull request, thanks for looking out!

**Pull request closed without merging**
